image: golang:1.17-buster

stages:
  - build
  - test
  - dockerize
  - gkedeploy

build application:
  stage: build
  script:
    - go build -o ./server
  artifacts:
    paths:
      - ./server

test application:
  stage: test
  script:
    - go test

dockerize application:
  image: docker
  stage: dockerize
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --tag $CI_REGISTRY_USER/$REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_USER/$REGISTRY_IMAGE

deploy application:
  stage: gkedeploy
  image: google/cloud-sdk
  script:
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone europe-west4-c --project $CLOUD_PROJECT_NAME
    - kubectl apply -f k8s/deployment.yaml