image: golang:1.17-buster

stages:
  - build
  - test
  - dockerize

build application:
  stage: build
  script:
    - go build -o ./server
  artifacts:
    paths:
      - ./server

test application:
  stage: test
  script:
    - go test

dockerize application:
  image: docker
  stage: dockerize
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --tag $CI_REGISTRY_USER/$REGISTRY_IMAGE .
    - docker push $REGISTRY_IMAGE